export const COUNTRY_OPTIONS = [
  { code: "", name: "All Countries" },
  { code: "af", name: "Afghanistan" },
  { code: "al", name: "Albania" },
  { code: "dz", name: "Algeria" },
  { code: "as", name: "American Samoa" },
  { code: "ad", name: "Andorra" },
  { code: "ao", name: "Angola" },
  { code: "ai", name: "Anguilla" },
  { code: "antarctica-city", name: "Antarctica" },
  { code: "ag", name: "Antigua and Barbuda" },
  { code: "ar", name: "Argentina" },
  { code: "am", name: "Armenia" },
  { code: "aw", name: "Aruba" },
  { code: "au", name: "Australia" },
  { code: "at", name: "Austria" },
  { code: "az", name: "Azerbaijan" },
  { code: "bs", name: "Bahamas" },
  { code: "bh", name: "Bahrain" },
  { code: "bd", name: "Bangladesh" },
  { code: "bb", name: "Barbados" },
  { code: "by", name: "Belarus" },
  { code: "be", name: "Belgium" },
  { code: "bz", name: "Belize" },
  { code: "bj", name: "Benin" },
  { code: "bm", name: "Bermuda" },
  { code: "bt", name: "Bhutan" },
  { code: "bo", name: "Bolivia" },
  { code: "ba", name: "Bosnia and Herzegovina" },
  { code: "bw", name: "Botswana" },
  { code: "br", name: "Brazil" },
  { code: "bn", name: "Brunei" },
  { code: "bg", name: "Bulgaria" },
  { code: "bf", name: "Burkina Faso" },
  { code: "bi", name: "Burundi" },
  { code: "kh", name: "Cambodia" },
  { code: "cm", name: "Cameroon" },
  { code: "ca", name: "Canada" },
  { code: "cv", name: "Cape Verde" },
  { code: "ky", name: "Cayman Islands" },
  { code: "cf", name: "Central African Republic" },
  { code: "td", name: "Chad" },
  { code: "cl", name: "Chile" },
  { code: "cn", name: "China" },
  { code: "co", name: "Colombia" },
  { code: "cr", name: "Costa Rica" },
  { code: "ci", name: "Ivory Coast" },
  { code: "hr", name: "Croatia" },
  { code: "cub", name: "Cuba" },
  { code: "cw", name: "Curacao" },
  { code: "cy", name: "Cyprus" },
  { code: "cz", name: "Czech Republic" },
  { code: "dk", name: "Denmark" },
  { code: "dj", name: "Djibouti" },
  { code: "dm", name: "Dominica" },
  { code: "do", name: "Dominican Republic" },
  { code: "ec", name: "Ecuador" },
  { code: "eg", name: "Egypt" },
  { code: "sv", name: "El Salvador" },
  { code: "gq", name: "Equatorial Guinea" },
  { code: "er", name: "Eritrea" },
  { code: "ee", name: "Estonia" },
  { code: "sz", name: "Eswatini" },
  { code: "et", name: "Ethiopia" },
  { code: "fk", name: "Falkland Islands" },
  { code: "fo", name: "Faroe Islands" },
  { code: "pf", name: "French Polynesia" },
  { code: "ga", name: "Gabon" },
  { code: "gm", name: "Gambia" },
  { code: "ge", name: "Georgia" },
  { code: "de", name: "Germany" },
  { code: "gh", name: "Ghana" },
  { code: "gi", name: "Gibraltar" },
  { code: "gr", name: "Greece" },
  { code: "gl", name: "Greenland" },
  { code: "gd", name: "Grenada" },
  { code: "gp", name: "Guadeloupe" },
  { code: "gt", name: "Guatemala" },
  { code: "gn", name: "Guinea" },
  { code: "gw", name: "Guinea‑Bissau" },
  { code: "gy", name: "Guyana" },
  { code: "ht", name: "Haiti" },
  { code: "hn", name: "Honduras" },
  { code: "hk", name: "Hong Kong" },
  { code: "hu", name: "Hungary" },
  { code: "is", name: "Iceland" },
  { code: "in", name: "India" },
  { code: "id", name: "Indonesia" },
  { code: "ir", name: "Iran" },
  { code: "iq", name: "Iraq" },
  { code: "ie", name: "Ireland" },
  { code: "il", name: "Israel" },
  { code: "it", name: "Italy" },
  { code: "ci", name: "Ivory Coast" },
  { code: "jm", name: "Jamaica" },
  { code: "jp", name: "Japan" },
  { code: "jo", name: "Jordan" },
  { code: "kz", name: "Kazakhstan" },
  { code: "ke", name: "Kenya" },
  { code: "ki", name: "Kiribati" },
  { code: "kw", name: "Kuwait" },
  { code: "kg", name: "Kyrgyzstan" },
  { code: "la", name: "Laos" },
  { code: "lv", name: "Latvia" },
  { code: "lb", name: "Lebanon" },
  { code: "ls", name: "Lesotho" },
  { code: "lr", name: "Liberia" },
  { code: "ly", name: "Libya" },
  { code: "li", name: "Liechtenstein" },
  { code: "lt", name: "Lithuania" },
  { code: "lu", name: "Luxembourg" },
  { code: "mo", name: "Macau" },
  { code: "mk", name: "North Macedonia" },
  { code: "mg", name: "Madagascar" },
  { code: "mw", name: "Malawi" },
  { code: "my", name: "Malaysia" },
  { code: "mv", name: "Maldives" },
  { code: "ml", name: "Mali" },
  { code: "mt", name: "Malta" },
  { code: "mr", name: "Mauritania" },
  { code: "mu", name: "Mauritius" },
  { code: "mx", name: "Mexico" },
  { code: "md", name: "Moldova" },
  { code: "mc", name: "Monaco" },
  { code: "mn", name: "Mongolia" },
  { code: "me", name: "Montenegro" },
  { code: "ms", name: "Montserrat" },
  { code: "ma", name: "Morocco" },
  { code: "mz", name: "Mozambique" },
  { code: "mm", name: "Myanmar" },
  { code: "na", name: "Namibia" },
  { code: "nr", name: "Nauru" },
  { code: "np", name: "Nepal" },
  { code: "nl", name: "Netherlands" },
  { code: "nc", name: "New Caledonia" },
  { code: "nz", name: "New Zealand" },
  { code: "ni", name: "Nicaragua" },
  { code: "ne", name: "Niger" },
  { code: "ng", name: "Nigeria" },
  { code: "kp", name: "North Korea" },
  { code: "mp", name: "Northern Mariana Islands" },
  { code: "no", name: "Norway" },
  { code: "om", name: "Oman" },
  { code: "pk", name: "Pakistan" },
  { code: "pw", name: "Palau" },
  { code: "pa", name: "Panama" },
  { code: "py", name: "Paraguay" },
  { code: "pe", name: "Peru" },
  { code: "ph", name: "Philippines" },
  { code: "pl", name: "Poland" },
  { code: "pt", name: "Portugal" },
  { code: "ps", name: "Palestine" },
  { code: "re", name: "Reunion" },
  { code: "ro", name: "Romania" },
  { code: "ru", name: "Russia" },
  { code: "rw", name: "Rwanda" },
  { code: "kn", name: "Saint Kitts and Nevis" },
  { code: "lc", name: "Saint Lucia" },
  { code: "mf", name: "Saint Martin" },
  { code: "pm", name: "Saint Pierre and Miquelon" },
  { code: "st", name: "Sao Tome and Principe" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "sn", name: "Senegal" },
  { code: "rs", name: "Serbia" },
  { code: "sc", name: "Seychelles" },
  { code: "sl", name: "Sierra Leone" },
  { code: "sg", name: "Singapore" },
  { code: "sk", name: "Slovakia" },
  { code: "si", name: "Slovenia" },
  { code: "sb", name: "Solomon Islands" },
  { code: "so", name: "Somalia" },
  { code: "za", name: "South Africa" },
  { code: "kr", name: "South Korea" },
  { code: "ss", name: "South Sudan" },
  { code: "es", name: "Spain" },
  { code: "lk", name: "Sri Lanka" },
  { code: "sd", name: "Sudan" },
  { code: "sr", name: "Suriname" },
  { code: "sj", name: "Sweden" },
  { code: "ch", name: "Switzerland" },
  { code: "sy", name: "Syria" },
  { code: "tw", name: "Taiwan" },
  { code: "tj", name: "Tajikistan" },
  { code: "th", name: "Thailand" },
  { code: "tl", name: "Timor‑Leste" },
  { code: "tg", name: "Togo" },
  { code: "to", name: "Tonga" },
  { code: "tc", name: "Turks and Caicos Islands" },
  { code: "tt", name: "Trinidad and Tobago" },
  { code: "tn", name: "Tunisia" },
  { code: "tr", name: "Turkey" },
  { code: "tm", name: "Turkmenistan" },
  { code: "tv", name: "Tuvalu" },
  { code: "ae", name: "United Arab Emirates" },
  { code: "ug", name: "Uganda" },
  { code: "ua", name: "Ukraine" },
  { code: "gb", name: "United Kingdom" },
  { code: "us", name: "United States" },
  { code: "vi", name: "United States Virgin Islands" },
  { code: "uy", name: "Uruguay" },
  { code: "uz", name: "Uzbekistan" },
  { code: "vu", name: "Vanuatu" },
  { code: "ve", name: "Venezuela" },
  { code: "vn", name: "Vietnam" },
  { code: "wf", name: "Wallis and Futuna" },
  { code: "eh", name: "Western Sahara" },
  { code: "ye", name: "Yemen" },
  { code: "zm", name: "Zambia" },
  { code: "zw", name: "Zimbabwe" },
];


export const COUNTRY_TO_CURRENCY = {
    // Africa
    "Algeria": "DZD",
    "Angola": "AOA",
    "Benin": "XOF",
    "Botswana": "BWP",
    "Burkina Faso": "XOF",
    "Burundi": "BIF",
    "Cameroon": "XAF",
    "Cape Verde": "CVE",
    "Central African Republic": "XAF",
    "Chad": "XAF",
    "Comoros": "KMF",
    "Djibouti": "DJF",
    "DR Congo": "CDF",
    "Egypt": "EGP",
    "Equatorial Guinea": "XAF",
    "Eritrea": "ERN",
    "Eswatini": "SZL",
    "Ethiopia": "ETB",
    "Gabon": "XAF",
    "Gambia": "GMD",
    "Ghana": "GHS",
    "Guinea": "GNF",
    "Guinea-Bissau": "XOF",
    "Ivory Coast": "XOF",
    "Kenya": "KES",
    "Lesotho": "LSL",
    "Liberia": "LRD",
    "Libya": "LYD",
    "Madagascar": "MGA",
    "Malawi": "MWK",
    "Mali": "XOF",
    "Mauritania": "MRU",
    "Mauritius": "MUR",
    "Mayotte": "EUR",
    "Morocco": "MAD",
    "Mozambique": "MZN",
    "Namibia": "NAD",
    "Niger": "XOF",
    "Nigeria": "NGN",
    "Republic of the Congo": "XAF",
    "Reunion": "EUR",
    "Rwanda": "RWF",
    "Sao Tome and Principe": "STN",
    "Senegal": "XOF",
    "Seychelles": "SCR",
    "Sierra Leone": "SLL",
    "Somalia": "SOS",
    "South Africa": "ZAR",
    "South Sudan": "SSP",
    "Sudan": "SDG",
    "Tanzania": "TZS",
    "Togo": "XOF",
    "Tunisia": "TND",
    "Uganda": "UGX",
    "Western Sahara": "MAD",
    "Zambia": "ZMW",
    "Zimbabwe": "ZWL",

    // Antarctica (no local currency)
    "Antarctica": "USD",

    // Asia
    "Afghanistan": "AFN",
    "Armenia": "AMD",
    "Azerbaijan": "AZN",
    "Bahrain": "BHD",
    "Bangladesh": "BDT",
    "Bhutan": "BTN",
    "Brunei": "BND",
    "Cambodia": "KHR",
    "China": "CNY",
    "Georgia": "GEL",
    "Hong Kong": "HKD",
    "India": "INR",
    "Indonesia": "IDR",
    "Iran": "IRR",
    "Iraq": "IQD",
    "Israel": "ILS",
    "Japan": "JPY",
    "Jordan": "JOD",
    "Kazakhstan": "KZT",
    "Kuwait": "KWD",
    "Kyrgyzstan": "KGS",
    "Laos": "LAK",
    "Lebanon": "LBP",
    "Macau": "MOP",
    "Malaysia": "MYR",
    "Maldives": "MVR",
    "Mongolia": "MNT",
    "Myanmar": "MMK",
    "Nepal": "NPR",
    "North Korea": "KPW",
    "Oman": "OMR",
    "Pakistan": "PKR",
    "Palestine": "ILS",
    "Philippines": "PHP",
    "Qatar": "QAR",
    "Saudi Arabia": "SAR",
    "Singapore": "SGD",
    "South Korea": "KRW",
    "Sri Lanka": "LKR",
    "Syria": "SYP",
    "Taiwan": "TWD",
    "Tajikistan": "TJS",
    "Thailand": "THB",
    "Timor-Leste": "USD",
    "Turkey": "TRY",
    "Turkmenistan": "TMT",
    "United Arab Emirates": "AED",
    "Uzbekistan": "UZS",
    "Vietnam": "VND",
    "Yemen": "YER",

    // Europe
    "Albania": "ALL",
    "Andorra": "EUR",
    "Austria": "EUR",
    "Belarus": "BYN",
    "Belgium": "EUR",
    "Bosnia and Herzegovina": "BAM",
    "Bulgaria": "BGN",
    "Croatia": "EUR",
    "Cyprus": "EUR",
    "Czech Republic": "CZK",
    "Denmark": "DKK",
    "Estonia": "EUR",
    "Faroe Islands": "DKK",
    "Finland": "EUR",
    "France": "EUR",
    "Germany": "EUR",
    "Gibraltar": "GIP",
    "Greece": "EUR",
    "Guernsey": "GBP",
    "Hungary": "HUF",
    "Iceland": "ISK",
    "Ireland": "EUR",
    "Isle of Man": "GBP",
    "Italy": "EUR",
    "Jersey": "GBP",
    "Latvia": "EUR",
    "Liechtenstein": "CHF",
    "Lithuania": "EUR",
    "Luxembourg": "EUR",
    "Malta": "EUR",
    "Moldova": "MDL",
    "Monaco": "EUR",
    "Montenegro": "EUR",
    "Netherlands": "EUR",
    "North Macedonia": "MKD",
    "Norway": "NOK",
    "Poland": "PLN",
    "Portugal": "EUR",
    "Romania": "RON",
    "Russia": "RUB",
    "San Marino": "EUR",
    "Serbia": "RSD",
    "Slovakia": "EUR",
    "Slovenia": "EUR",
    "Spain": "EUR",
    "Sweden": "SEK",
    "Switzerland": "CHF",
    "Ukraine": "UAH",
    "United Kingdom": "GBP",
    "Vatican City": "EUR",

    // North America & Caribbean
    "Anguilla": "XCD",
    "Antigua and Barbuda": "XCD",
    "Aruba": "AWG",
    "Bahamas": "BSD",
    "Barbados": "BBD",
    "Belize": "BZD",
    "Bermuda": "BMD",
    "British Virgin Islands": "USD",
    "Canada": "CAD",
    "Cayman Islands": "KYD",
    "Costa Rica": "CRC",
    "Cuba": "CUP",
    "Curacao": "ANG",
    "Dominica": "XCD",
    "Dominican Republic": "DOP",
    "El Salvador": "USD",
    "Greenland": "DKK",
    "Grenada": "XCD",
    "Guadeloupe": "EUR",
    "Guatemala": "GTQ",
    "Haiti": "HTG",
    "Honduras": "HNL",
    "Jamaica": "JMD",
    "Martinique": "EUR",
    "Mexico": "MXN",
    "Montserrat": "XCD",
    "Nicaragua": "NIO",
    "Panama": "PAB",
    "Puerto Rico": "USD",
    "Saint Barthelemy": "EUR",
    "Saint Kitts and Nevis": "XCD",
    "Saint Lucia": "XCD",
    "Saint Martin": "EUR",
    "Saint Pierre and Miquelon": "EUR",
    "Saint Vinent and the Grenadines": "XCD",
    "Sint Maarten": "ANG",
    "Trinidad and Tobago": "TTD",
    "Turks and Caicos Islands": "USD",
    "United States": "USD",
    "United States Virgin Islands": "USD",

    // Oceania
    "American Samoa": "USD",
    "Australia": "AUD",
    "Cook Islands": "NZD",
    "Fiji": "FJD",
    "French Polynesia": "XPF",
    "Guam": "USD",
    "Kiribati": "AUD",
    "Marshall Islands": "USD",
    "Micronesia": "USD",
    "Nauru": "AUD",
    "New Caledonia": "XPF",
    "New Zealand": "NZD",
    "Niue": "NZD",
    "Northern Mariana Islands": "USD",
    "Palau": "USD",
    "Papua New Guinea": "PGK",
    "Samoa": "WST",
    "Solomon Islands": "SBD",
    "Tokelau": "NZD",
    "Tonga": "TOP",
    "Tuvalu": "AUD",
    "Vanuatu": "VUV",
    "Wallis and Futuna": "XPF",

    // South America
    "Argentina": "ARS",
    "Bolivia": "BOB",
    "Brazil": "BRL",
    "Chile": "CLP",
    "Colombia": "COP",
    "Ecuador": "USD",
    "Falkland Islands": "FKP",
    "French Guiana": "EUR",
    "Guyana": "GYD",
    "Paraguay": "PYG",
    "Peru": "PEN",
    "Suriname": "SRD",
    "Uruguay": "UYU",
    "Venezuela": "VES",
  };
  export const CURRENCY_OPTIONS = [
    { code: "USD", name: "US Dollar" },
    { code: "EUR", name: "Euro" },
    { code: "SEK", name: "Swedish Krona" },
    { code: "GBP", name: "British Pound" },
    { code: "THB", name: "Thai Baht" },
    { code: "JPY", name: "Japanese Yen" },
    { code: "DZD", name: "Algerian Dinar" },
    { code: "AOA", name: "Angolan Kwanza" },
    { code: "XOF", name: "West African CFA Franc" },
    { code: "BWP", name: "Botswana Pula" },
    { code: "BIF", name: "Burundian Franc" },
    { code: "XAF", name: "Central African CFA Franc" },
    { code: "CVE", name: "Cape Verdean Escudo" },
    { code: "KMF", name: "Comorian Franc" },
    { code: "DJF", name: "Djiboutian Franc" },
    { code: "CDF", name: "Congolese Franc" },
    { code: "EGP", name: "Egyptian Pound" },
    { code: "ERN", name: "Eritrean Nakfa" },
    { code: "SZL", name: "Swazi Lilangeni" },
    { code: "ETB", name: "Ethiopian Birr" },
    { code: "GMD", name: "Gambian Dalasi" },
    { code: "GHS", name: "Ghanaian Cedi" },
    { code: "GNF", name: "Guinean Franc" },
    { code: "KES", name: "Kenyan Shilling" },
    { code: "LSL", name: "Lesotho Loti" },
    { code: "LRD", name: "Liberian Dollar" },
    { code: "LYD", name: "Libyan Dinar" },
    { code: "MGA", name: "Malagasy Ariary" },
    { code: "MWK", name: "Malawian Kwacha" },
    { code: "MRU", name: "Mauritanian Ouguiya" },
    { code: "MUR", name: "Mauritian Rupee" },
    { code: "MAD", name: "Moroccan Dirham" },
    { code: "MZN", name: "Mozambican Metical" },
    { code: "NAD", name: "Namibian Dollar" },
    { code: "NGN", name: "Nigerian Naira" },
    { code: "RWF", name: "Rwandan Franc" },
    { code: "STN", name: "São Tomé and Príncipe Dobra" },
    { code: "SCR", name: "Seychellois Rupee" },
    { code: "SLL", name: "Sierra Leonean Leone" },
    { code: "SOS", name: "Somali Shilling" },
    { code: "ZAR", name: "South African Rand" },
    { code: "SSP", name: "South Sudanese Pound" },
    { code: "SDG", name: "Sudanese Pound" },
    { code: "TZS", name: "Tanzanian Shilling" },
    { code: "TND", name: "Tunisian Dinar" },
    { code: "UGX", name: "Ugandan Shilling" },
    { code: "ZMW", name: "Zambian Kwacha" },
    { code: "ZWL", name: "Zimbabwean Dollar" },
    { code: "AFN", name: "Afghan Afghani" },
    { code: "AMD", name: "Armenian Dram" },
    { code: "AZN", name: "Azerbaijani Manat" },
    { code: "BHD", name: "Bahraini Dinar" },
    { code: "BDT", name: "Bangladeshi Taka" },
    { code: "BTN", name: "Bhutanese Ngultrum" },
    { code: "BND", name: "Brunei Dollar" },
    { code: "KHR", name: "Cambodian Riel" },
    { code: "CNY", name: "Chinese Yuan" },
    { code: "GEL", name: "Georgian Lari" },
    { code: "HKD", name: "Hong Kong Dollar" },
    { code: "INR", name: "Indian Rupee" },
    { code: "IDR", name: "Indonesian Rupiah" },
    { code: "IRR", name: "Iranian Rial" },
    { code: "IQD", name: "Iraqi Dinar" },
    { code: "ILS", name: "Israeli New Shekel" },
    { code: "JOD", name: "Jordanian Dinar" },
    { code: "KZT", name: "Kazakhstani Tenge" },
    { code: "KWD", name: "Kuwaiti Dinar" },
    { code: "KGS", name: "Kyrgyzstani Som" },
    { code: "LAK", name: "Lao Kip" },
    { code: "LBP", name: "Lebanese Pound" },
    { code: "MOP", name: "Macanese Pataca" },
    { code: "MYR", name: "Malaysian Ringgit" },
    { code: "MVR", name: "Maldivian Rufiyaa" },
    { code: "MNT", name: "Mongolian Tögrög" },
    { code: "MMK", name: "Burmese Kyat" },
    { code: "NPR", name: "Nepalese Rupee" },
    { code: "KPW", name: "North Korean Won" },
    { code: "OMR", name: "Omani Rial" },
    { code: "PKR", name: "Pakistani Rupee" },
    { code: "PHP", name: "Philippine Peso" },
    { code: "QAR", name: "Qatari Riyal" },
    { code: "SAR", name: "Saudi Riyal" },
    { code: "SGD", name: "Singapore Dollar" },
    { code: "KRW", name: "South Korean Won" },
    { code: "LKR", name: "Sri Lankan Rupee" },
    { code: "SYP", name: "Syrian Pound" },
    { code: "TWD", name: "New Taiwan Dollar" },
    { code: "TJS", name: "Tajikistani Somoni" },
    { code: "TRY", name: "Turkish Lira" },
    { code: "TMT", name: "Turkmenistani Manat" },
    { code: "AED", name: "UAE Dirham" },
    { code: "UZS", name: "Uzbekistani So'm" },
    { code: "VND", name: "Vietnamese Dong" },
    { code: "YER", name: "Yemeni Rial" },
    { code: "ALL", name: "Albanian Lek" },
    { code: "BYN", name: "Belarusian Ruble" },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
    { code: "BGN", name: "Bulgarian Lev" },
    { code: "CZK", name: "Czech Koruna" },
    { code: "DKK", name: "Danish Krone" },
    { code: "HUF", name: "Hungarian Forint" },
    { code: "ISK", name: "Icelandic Krona" },
    { code: "MDL", name: "Moldovan Leu" },
    { code: "MKD", name: "Macedonian Denar" },
    { code: "NOK", name: "Norwegian Krone" },
    { code: "PLN", name: "Polish Zloty" },
    { code: "RON", name: "Romanian Leu" },
    { code: "RUB", name: "Russian Ruble" },
    { code: "CHF", name: "Swiss Franc" },
    { code: "RSD", name: "Serbian Dinar" },
    { code: "UAH", name: "Ukrainian Hryvnia" },
    { code: "XCD", name: "East Caribbean Dollar" },
    { code: "AWG", name: "Aruban Florin" },
    { code: "BSD", name: "Bahamian Dollar" },
    { code: "BBD", name: "Barbadian Dollar" },
    { code: "BZD", name: "Belize Dollar" },
    { code: "BMD", name: "Bermudian Dollar" },
    { code: "CAD", name: "Canadian Dollar" },
    { code: "KYD", name: "Cayman Islands Dollar" },
    { code: "CRC", name: "Costa Rican Colón" },
    { code: "CUP", name: "Cuban Peso" },
    { code: "ANG", name: "Netherlands Antillean Guilder" },
    { code: "DOP", name: "Dominican Peso" },
    { code: "GTQ", name: "Guatemalan Quetzal" },
    { code: "HTG", name: "Haitian Gourde" },
    { code: "HNL", name: "Honduran Lempira" },
    { code: "JMD", name: "Jamaican Dollar" },
    { code: "MXN", name: "Mexican Peso" },
    { code: "NIO", name: "Nicaraguan Córdoba" },
    { code: "PAB", name: "Panamanian Balboa" },
    { code: "TTD", name: "Trinidad and Tobago Dollar" },
    { code: "SBD", name: "Solomon Islands Dollar" },
    { code: "TOP", name: "Tongan Paʻanga" },
    { code: "VUV", name: "Vanuatu Vatu" },
    { code: "ARS", name: "Argentine Peso" },
    { code: "BOB", name: "Bolivian Boliviano" },
    { code: "BRL", name: "Brazilian Real" },
    { code: "CLP", name: "Chilean Peso" },
    { code: "COP", name: "Colombian Peso" },
    { code: "FKP", name: "Falkland Islands Pound" },
    { code: "GYD", name: "Guyanese Dollar" },
    { code: "PYG", name: "Paraguayan Guarani" },
    { code: "PEN", name: "Peruvian Sol" },
    { code: "SRD", name: "Surinamese Dollar" },
    { code: "UYU", name: "Uruguayan Peso" },
    { code: "VES", name: "Venezuelan Bolívar" },
    { code: "XPF", name: "CFP Franc" },
    { code: "NZD", name: "New Zealand Dollar" },
    { code: "WST", name: "Samoan Tala" },
  ];