// Material Dashboard 2 React page components (no layout imports)
import React from "react";
import Tables from "./layouts/tables";
import Billing from "./layouts/billing";
import RTL from "./layouts/rtl";
import Notifications from "./layouts/notifications";
import Profile from "./layouts/profile";
import SignIn from "./layouts/authentication/sign-in";
import SignUp from "./layouts/authentication/sign-up";
import LocationOnIcon from '@mui/icons-material/LocationOn';
import PublicIcon from '@mui/icons-material/Public';
import CityPage from "components/CityPage";
import Home from "layouts/home";
import HomeIcon from "@mui/icons-material/Home";
import CountryPage from "components/countries/CountryPage";
import ContinentPage from "components/continent/ContinentPage";
import PinPage from "components/PinPage";
// @mui icons
import Icon from "@mui/material/Icon";


const Map = React.lazy(() => import("./layouts/map"));

const routes = [
  {
    type: "collapse",
    name: "Home",
    key: "home",
    icon: <HomeIcon fontSize="small">dashboard</HomeIcon>,
    route: "/home",
    component: Home,
  },
  {
    type: "collapse",
    name: "Map",
    key: "map",
    icon: <PublicIcon fontsize="small" />,
    route: "/map",
    component: Map,
  },
  {
    type: "collapse",
    name: "Destinations",
    key: "destinations",
    icon: <LocationOnIcon fontSize="small" />,
    flyout: false,
    children: [
      {
        type: "collapse",
        name: "Africa",
        key: "africa",
        flyout: false,
        route: "/Destinations/World_destinations/Africa",
        sx: { backgroundColor: "#F18F01" },
        component: ContinentPage,
        children: [
          { name: "Algeria", key: "dz",  route: "/Destinations/World_destinations/Africa/Algeria" },
          { name: "Angola", key: "ao",  route: "/Destinations/World_destinations/Africa/Angola" },
          { name: "Benin", key: "bj",  route: "/Destinations/World_destinations/Africa/Benin" },
          { name: "Botswana", key: "bw",  route: "/Destinations/World_destinations/Africa/Botswana" },
          { name: "Burkina Faso", key: "bf",  route: "/Destinations/World_destinations/Africa/Burkina_Faso" },
          { name: "Burundi", key: "bi",  route: "/Destinations/World_destinations/Africa/Burundi" },
          { name: "Cameroon", key: "cm",  route: "/Destinations/World_destinations/Africa/Cameroon" },
          { name: "Cape Verde", key: "cv",  route: "/Destinations/World_destinations/Africa/Cape_Verde" },
          { name: "Central African Republic", key: "cf",  route: "/Destinations/World_destinations/Africa/Central_African_Republic" },
          { name: "Chad", key: "td",  route: "/Destinations/World_destinations/Africa/Chad" },
          { name: "Comoos", key: "km",  route: "/Destinations/World_destinations/Africa/Comoros" },
          { name: "Djibouti", key: "dj",  route: "/Destinations/World_destinations/Africa/Djibouti" },
          { name: "DR Congo", key: "cd",  route: "/Destinations/World_destinations/Africa/DR_Congo" },
          { name: "Egypt", key: "eg",  route: "/Destinations/World_destinations/Africa/Egypt" },
          { name: "Equatorial Guinea", key: "gq",  route: "/Destinations/World_destinations/Africa/Equatorial_Guinea" },
          { name: "Eritrea", key: "er",  route: "/Destinations/World_destinations/Africa/Eritrea" },
          { name: "Eswatini", key: "sz",  route: "/Destinations/World_destinations/Africa/Eswatini" },
          { name: "Ethiopia", key: "et",  route: "/Destinations/World_destinations/Africa/Ethiopia" },
          { name: "Gabon", key: "ga",  route: "/Destinations/World_destinations/Africa/Gabon" },
          { name: "Gambia", key: "gm",  route: "/Destinations/World_destinations/Africa/Gambia" },
          { name: "Ghana", key: "gh",  route: "/Destinations/World_destinations/Africa/Ghana" },
          { name: "Guinea", key: "gn",  route: "/Destinations/World_destinations/Africa/Guinea" },
          { name: "Guinea-Bissau", key: "gw",  route: "/Destinations/World_destinations/Africa/Guinea_Bissau" },
          { name: "Ivory Coast", key: "ci",  route: "/Destinations/World_destinations/Africa/Ivory_Coast" },
          { name: "Kenya", key: "ke",  route: "/Destinations/World_destinations/Africa/Kenya" },
          { name: "Lesotho", key: "ls",  route: "/Destinations/World_destinations/Africa/Lesotho" },
          { name: "Liberia", key: "lr",  route: "/Destinations/World_destinations/Africa/Liberia" },
          { name: "Libya", key: "ly",  route: "/Destinations/World_destinations/Africa/Libya" },
          { name: "Madagascar", key: "mg",  route: "/Destinations/World_destinations/Africa/Madagascar" },
          { name: "Malawi", key: "mw",  route: "/Destinations/World_destinations/Africa/Malawi" },
          { name: "Mali", key: "ml",  route: "/Destinations/World_destinations/Africa/Mali" },
          { name: "Mauritania", key: "mr",  route: "/Destinations/World_destinations/Africa/Mauritania" },
          { name: "Mauritius", key: "mu",  route: "/Destinations/World_destinations/Africa/Mauritius" },
          { name: "Mayotte", key: "yt",  route: "/Destinations/World_destinations/Africa/Mayotte" },
          { name: "Morocco", key: "ma",  route: "/Destinations/World_destinations/Africa/Morocco" },
          { name: "Mozambique", key: "mz",  route: "/Destinations/World_destinations/Africa/Mozambique" },
          { name: "Namibia", key: "na",  route: "/Destinations/World_destinations/Africa/Namibia" },
          { name: "Niger", key: "ne",  route: "/Destinations/World_destinations/Africa/Niger" },
          { name: "Nigeria", key: "ng",  route: "/Destinations/World_destinations/Africa/Nigeria" },
          { name: "Republic of the Congo", key: "cg",  route: "/Destinations/World_destinations/Africa/Republic_of_the_Congo" },
          { name: "Reunion", key: "re",  route: "/Destinations/World_destinations/Africa/Reunion" },
          { name: "Rwanda", key: "rw",  route: "/Destinations/World_destinations/Africa/Rwanda" },
          { name: "Sao Tome and Principe", key: "st",  route: "/Destinations/World_destinations/Africa/Sao_Tome_and_principe" },
          { name: "Senegal", key: "sn",  route: "/Destinations/World_destinations/Africa/Senegal" },
          { name: "Seychelles", key: "sc",  route: "/Destinations/World_destinations/Africa/Seychelles" },
          { name: "Sierra Leone", key: "sl",  route: "/Destinations/World_destinations/Africa/Sierra_Leone" },
          { name: "Somalia", key: "so",  route: "/Destinations/World_destinations/Africa/Somalia" },
          { name: "South Africa", key: "za",  route: "/Destinations/World_destinations/Africa/South_Africa" },
          { name: "South Sudan", key: "ss",  route: "/Destinations/World_destinations/Africa/South_Sudan" },
          { name: "Sudan", key: "sd",  route: "/Destinations/World_destinations/Africa/Sudan" },
          { name: "Tanzania", key: "tz",  route: "/Destinations/World_destinations/Africa/Tanzania" },
          { name: "Togo", key: "tg",  route: "/Destinations/World_destinations/Africa/Togo" },
          { name: "Tunisia", key: "tn",  route: "/Destinations/World_destinations/Africa/Tunisia" },
          { name: "Uganda", key: "ug",  route: "/Destinations/World_destinations/Africa/Uganda" },
          { name: "Western Sahara", key: "eh",  route: "/Destinations/World_destinations/Africa/Western_Sahara" },
          { name: "Zambia", key: "zm",  route: "/Destinations/World_destinations/Africa/Zambia" },
          { name: "Zimbabwe", key: "zw", route: "/Destinations/World_destinations/Africa/Zimbabwe" },
        ]
      },
      {
        type: "collapse",
        name: "Antarctica",
        key: "antarctica",
        flyout: false,
        route: "/Destinations/World_destinations/Antarctica",
        sx: { backgroundColor: "#F18F01" },
        component: ContinentPage,
        children: [
          { name: "Antarctica", key: "antarctica-city", route: "/Destinations/World_destinations/Antarctica/Antarctica" }
        ]
      },
      {
        type: "collapse",
        name: "Asia",
        key: "asia",
        route: "/Destinations/World_destinations/Asia",
        component: ContinentPage,
        flyout: false,
        route: "/Destinations/World_destinations/Asia",
        sx: { backgroundColor: "#F18F01" },
        component: ContinentPage,
        children: [
          { name: "Afghanistan", key: "af", route: "/Destinations/World_destinations/Asia/Afghanistan" },
          { name: "Armenia", key: "am", route: "/Destinations/World_destinations/Asia/Armenia" },
          { name: "Azerbaijan", key: "az", route: "/Destinations/World_destinations/Asia/Azerbaijan" },
          { name: "Bahrain", key: "bh", route: "/Destinations/World_destinations/Asia/Bahrain" },
          { name: "Bangladesh", key: "bd", route: "/Destinations/World_destinations/Asia/Bangladesh" },
          { name: "Bhutan", key: "bt", route: "/Destinations/World_destinations/Asia/Bhutan" },
          { name: "Brunei", key: "bn", route: "/Destinations/World_destinations/Asia/Brunei" },
          { name: "Cambodia", key: "kh", route: "/Destinations/World_destinations/Asia/Cambodia" },
          { name: "China", key: "cn", route: "/Destinations/World_destinations/Asia/China" },
          { name: "Georgia", key: "ge", route: "/Destinations/World_destinations/Asia/Georgia" },
          { name: "Hong Kong", key: "hk", route: "/Destinations/World_destinations/Asia/Hong_Kong" },
          { name: "India", key: "in", route: "/Destinations/World_destinations/Asia/India" },
          { name: "Indonesia", key: "id", route: "/Destinations/World_destinations/Asia/Indonesia" },
          { name: "Iran", key: "ir", route: "/Destinations/World_destinations/Asia/Iran" },
          { name: "Iraq", key: "iq", route: "/Destinations/World_destinations/Asia/Iraq" },
          { name: "Israel", key: "il", route: "/Destinations/World_destinations/Asia/Israel" },
          { name: "Japan", key: "jp", route: "/Destinations/World_destinations/Asia/Japan" },
          { name: "Jordan", key: "jo", route: "/Destinations/World_destinations/Asia/Jordan" },
          { name: "Kazakhstan", key: "kz", route: "/Destinations/World_destinations/Asia/Kazakhsan" },
          { name: "Kuwait", key: "kw", route: "/Destinations/World_destinations/Asia/Kuwait" },
          { name: "Kyrgyzstan", key: "kg", route: "/Destinations/World_destinations/Asia/Kyrgyzstan" },
          { name: "Laos", key: "la", route: "/Destinations/World_destinations/Asia/Laos" },
          { name: "Lebanon", key: "lb", route: "/Destinations/World_destinations/Asia/Lebanon" },
          { name: "Macau", key: "mo", route: "/Destinations/World_destinations/Asia/Macau" },
          { name: "Malaysia", key: "my", route: "/Destinations/World_destinations/Asia/Malaysia" },
          { name: "Maldives", key: "mv", route: "/Destinations/World_destinations/Asia/Maldives" },
          { name: "Mongolia", key: "mn", route: "/Destinations/World_destinations/Asia/Mongolia" },
          { name: "Myanmar", key: "mm", route: "/Destinations/World_destinations/Asia/Myanmar" },
          { name: "Nepal", key: "np", route: "/Destinations/World_destinations/Asia/Nepal" },
          { name: "North Korea", key: "kp", route: "/Destinations/World_destinations/Asia/North_Korea" },
          { name: "Oman", key: "om", route: "/Destinations/World_destinations/Asia/Oman" },
          { name: "Pakistan", key: "pk", route: "/Destinations/World_destinations/Asia/Pakistan" },
          { name: "Palestine", key: "ps", route: "/Destinations/World_destinations/Asia/Palestine" },
          { name: "Philippines", key: "ph", route: "/Destinations/World_destinations/Asia/Philippines" },
          { name: "Qatar", key: "qa", route: "/Destinations/World_destinations/Asia/Qatar" },
          { name: "Saudi Arabia", key: "sa", route: "/Destinations/World_destinations/Asia/Saudi_Arabia" },
          { name: "Singapore", key: "sg", route: "/Destinations/World_destinations/Asia/Singapore" },
          { name: "South Korea", key: "kr", route: "/Destinations/World_destinations/Asia/South_Korea" },
          { name: "Sri Lanka", key: "lk", route: "/Destinations/World_destinations/Asia/Sri_Lanka" },
          { name: "Syria", key: "sy", route: "/Destinations/World_destinations/Asia/Syria" },
          { name: "Taiwan", key: "tw", route: "/Destinations/World_destinations/Asia/Taiwan" },
          { name: "Tajikistan", key: "tj", route: "/Destinations/World_destinations/Asia/Tajikistan" },
          { name: "Thailand", key: "th", route: "/Destinations/World_destinations/Asia/Thailand" },
          { name: "Timor-Leste", key: "tl", route: "/Destinations/World_destinations/Asia/Timor_Letse" },
          { name: "Turkey", key: "tr", route: "/Destinations/World_destinations/Asia/Turkey" },
          { name: "Turkmenistan", key: "tm", route: "/Destinations/World_destinations/Asia/Turkmenistan" },
          { name: "United Arab Emirates", key:"ae", route: "/Destinations/World_destinations/Asia/United_Arab_Emirates" },
          { name: "Uzbekistan", key: "uz", route: "/Destinations/World_destinations/Asia/Uzbekistan" },
          { name: "Vietnam", key: "vn", route: "/Destinations/World_destinations/Asia/Vietnam" },
          { name: "Yemen", key: "ye", route: "/Destinations/World_destinations/Asia/Yemen" },

        ]
      },
      {
        type: "collapse",
        name: "Europe",
        key: "europe",
        flyout: false,
        route: "/Destinations/World_destinations/Europe",
        sx: { backgroundColor: "#F18F01" },
        component: ContinentPage,
        children: [
          { name: "Albania", key: "al", route: "/Destinations/World_destinations/Europe/Albania" },
          { name: "Andorra", key: "ad", route: "/Destinations/World_destinations/Europe/Andorra" },
          { name: "Austria", key: "at", route: "/Destinations/World_destinations/Europe/Austria" },
          { name: "Belarus", key: "by", route: "/Destinations/World_destinations/Europe/Belarus" },
          { name: "Belgium", key: "be", route: "/Destinations/World_destinations/Europe/Belgium" },
          { name: "Bosnia and Herzegovina", key: "ba", route: "/Destinations/World_destinations/Europe/Bosnia_and_Herzegovina" },
          { name: "Bulgaria", key: "bg", route: "/Destinations/World_destinations/Europe/Bulgaria" },
          { name: "Croatia", key: "hr", route: "/Destinations/World_destinations/Europe/Croatia" },
          { name: "Cyprus", key: "cy", route: "/Destinations/World_destinations/Europe/Cyprus" },
          { name: "Czech Republic", key: "cz", route: "/Destinations/World_destinations/Europe/Czech_Republic" },
          { name: "Denmark", key: "dk", route: "/Destinations/World_destinations/Europe/Denmark" },
          { name: "Estonia", key: "ee", route: "/Destinations/World_destinations/Europe/Estonia" },
          { name: "Faroe Islands", key: "fo", route: "/Destinations/World_destinations/Europe/Faroe_Islands" },
          { name: "Finland", key: "fi", route: "/Destinations/World_destinations/Europe/Finland" },
          { name: "France", key: "fr", route: "/Destinations/World_destinations/Europe/France" },
          { name: "Germany", key: "de", route: "/Destinations/World_destinations/Europe/Germany" },
          { name: "Gibraltar", key: "gi", route: "/Destinations/World_destinations/Europe/Gibraltar" },
          { name: "Greece", key: "gr", route: "/Destinations/World_destinations/Europe/Greece" },
          { name: "Guernsey", key: "gg", route: "/Destinations/World_destinations/Europe/Guernsey" },
          { name: "Hungary", key: "hu", route: "/Destinations/World_destinations/Europe/Hungary" },
          { name: "Iceland", key: "is", route: "/Destinations/World_destinations/Europe/Iceland" },
          { name: "Ireland", key: "ie", route: "/Destinations/World_destinations/Europe/Ireland" },
          { name: "Isle of Man", key: "im", route: "/Destinations/World_destinations/Europe/Isle_of_Man" },
          { name: "Italy", key: "it", route: "/Destinations/World_destinations/Europe/Italy" },
          { name: "Jersey", key: "je", route: "/Destinations/World_destinations/Europe/Jersey" },
          { name: "Latvia", key: "lv", route: "/Destinations/World_destinations/Europe/Latvia" },
          { name: "Liechtenstein", key: "li", route: "/Destinations/World_destinations/Europe/Liechtenstein" },
          { name: "Lithuania", key: "lt", route: "/Destinations/World_destinations/Europe/Lithuania" },
          { name: "Luxembourg", key: "lu", route: "/Destinations/World_destinations/Europe/Luxembourg" },
          { name: "Malta", key: "mt", route: "/Destinations/World_destinations/Europe/Malta" },
          { name: "Moldova", key: "md", route: "/Destinations/World_destinations/Europe/Moldova" },
          { name: "Monaco", key: "mc", route: "/Destinations/World_destinations/Europe/Monaco" },
          { name: "Montenegro", key: "me", route: "/Destinations/World_destinations/Europe/Montenegro" },
          { name: "Netherlands", key: "nl", route: "/Destinations/World_destinations/Europe/Netherlands" },
          { name: "North Macedonia", key: "mk", route: "/Destinations/World_destinations/Europe/North_Macedonia" },
          { name: "Norway", key: "no", route: "/Destinations/World_destinations/Europe/Norway" },
          { name: "Poland", key: "pl", route: "/Destinations/World_destinations/Europe/Poland" },
          { name: "Portugal", key: "pt", route: "/Destinations/World_destinations/Europe/Portugal" },
          { name: "Romania", key: "ro", route: "/Destinations/World_destinations/Europe/Romania" },
          { name: "Russia", key: "ru", route: "/Destinations/World_destinations/Europe/Russia" },
          { name: "San Marino", key: "sm", route: "/Destinations/World_destinations/Europe/San_Marino" },
          { name: "Serbia", key: "rs", route: "/Destinations/World_destinations/Europe/Serbia" },
          { name: "Slovakia", key: "sk", route: "/Destinations/World_destinations/Europe/Slovakia" },
          { name: "Slovenia", key: "sl", route: "/Destinations/World_destinations/Europe/Slovenia" },
          { name: "Spain", key: "es", route: "/Destinations/World_destinations/Europe/Spain" },
          { name: "Sweden", key: "se", route: "/Destinations/World_destinations/Europe/Sweden" },
          { name: "Switzerland", key: "ch", route: "/Destinations/World_destinations/Europe/Switzerland" },
          { name: "Ukraine", key: "ua", route: "/Destinations/World_destinations/Europe/Ukraine" },
          { name: "United Kingdom", key: "gb", route: "/Destinations/World_destinations/Europe/United_Kingdom" },
          { name: "Vatican City", key: "va", route: "/Destinations/World_destinations/Europe/Vatican_City" },
        ]
      },    
      {
        type: "collapse",
        name: "North America",
        key: "north-america",
        flyout: false,
        route: "/Destinations/World_destinations/North_America",
        sx: { backgroundColor: "#F18F01" },
        component: ContinentPage,
        children: [
          { name: "Anguilla", key: "ai", route: "/Destinations/World_destinations/North_America/Anguilla" },
          { name: "Antigua and Barbuda", key: "ag", route: "/Destinations/World_destinations/North_America/Atigua_and_Barbuda" },
          { name: "Aruba", key: "aw", route: "/Destinations/World_destinations/North_America/Aruba" },
          { name: "Bahamas", key: "bs", route: "/Destinations/World_destinations/North_America/Bahamas" },
          { name: "Barbados", key: "bb", route: "/Destinations/World_destinations/North_America/Barbados" },
          { name: "Belize", key: "bz", route: "/Destinations/World_destinations/North_America/Belize" },
          { name: "Bermuda", key: "bm", route: "/Destinations/World_destinations/North_America/Bermuda" },
          { name: "British Virgin Islands", key: "vg", route: "/Destinations/World_destinations/North_America/British_Virgin_Islands" },
          { name: "Canada", key: "ca", route: "/Destinations/World_destinations/North_America/Canada" },
          { name: "Cayman Islands", key: "ky", route: "/Destinations/World_destinations/North_America/Cayman_Islands" },
          { name: "Costa Rica", key: "cr", route: "/Destinations/World_destinations/North_America/Costa_Rica" },
          { name: "Cuba", key: "cu", route: "/Destinations/World_destinations/North_America/Cuba" },
          { name: "Curacao", key: "cw", route: "/Destinations/World_destinations/North_America/Curacao" },
          { name: "Dominica", key: "dm", route: "/Destinations/World_destinations/North_America/Dominica" },
          { name: "Dominican Republic", key: "do", route: "/Destinations/World_destinations/North_America/Domenican_Republic" },
          { name: "El Salvador", key: "sv", route: "/Destinations/World_destinations/North_America/El_Salvador" },
          { name: "Greenland", key: "gl", route: "/Destinations/World_destinations/North_America/Greenland" },
          { name: "Grenada", key: "gd", route: "/Destinations/World_destinations/North_America/Grenada" },
          { name: "Guadeloupe", key: "gp", route: "/Destinations/World_destinations/North_America/Guadeloupe" },
          { name: "Guatemala", key: "gt", route: "/Destinations/World_destinations/North_America/Guatemala" },
          { name: "Haiti", key: "ht", route: "/Destinations/World_destinations/North_America/Haiti" },
          { name: "Honduras", key: "hn", route: "/Destinations/World_destinations/North_America/Honduras" },
          { name: "Jamaica", key: "jm", route: "/Destinations/World_destinations/North_America/Jamaica" },
          { name: "Martinique", key: "mq", route: "/Destinations/World_destinations/North_America/Martinique" },
          { name: "Mexico", key: "mx", route: "/Destinations/World_destinations/North_America/Mexico" },
          { name: "Montserrat", key: "ms", route: "/Destinations/World_destinations/North_America/Montserrat" },
          { name: "Nicaragua", key: "ni", route: "/Destinations/World_destinations/North_America/Nicaragua" },
          { name: "Panama", key: "pa", route: "/Destinations/World_destinations/North_America/Panama" },
          { name: "Puerto Rico", key: "pr", route: "/Destinations/World_destinations/North_America/Puerto_Rico" },
          { name: "Saint Barthelemy", key: "bl", route: "/Destinations/World_destinations/North_America/Saint_Barthelemy" },
          { name: "Saint Kitts and Nevis", key: "kn", route: "/Destinations/World_destinations/North_America/Saint_Kitts_and_Nevis" },
          { name: "Saint Lucia", key: "lc", route: "/Destinations/World_destinations/North_America/Saint_Lucia" },
          { name: "Saint Martin", key: "mf", route: "/Destinations/World_destinations/North_America/Saint_Martin" },
          { name: "Saint Pierre and Miquelon", key: "pm", route: "/Destinations/World_destinations/North_America/Saint_Pierre_and_Miquelon" },
          { name: "Saint Vinent and the Grenadines", key: "vc", route: "/Destinations/World_destinations/North_America/Saint_Vincent_and_the_Grenadines" },
          { name: "Sint Maarten", key: "sx", route: "/Destinations/World_destinations/North_America/Sint Maarten" },
          { name: "Trinidad and Tobago", key: "tt", route: "/Destinations/World_destinations/North_America/Trinidad and Tobago" },
          { name: "Turks and Caicos Islands", key: "tc", route: "/Destinations/World_destinations/North_America/Turks_and_Caicos_Islands" },
          { name: "United States", key: "us", route: "/Destinations/World_destinations/North_America/United_States" },
          { name: "United States Virgin Islands", key: "vi", route: "/Destinations/World_destinations/North_America/United_States_Virgin_Islands" },
        ]
      },
      {
        type: "collapse",
        name: "Oceania",
        key: "oceania",
        flyout: false,
        route: "/Destinations/World_destinations/Oceania",
        sx: { backgroundColor: "#F18F01" },
        component: ContinentPage,
        children: [
          { name: "American Samoa", key: "as", route: "/Destinations/World_destinations/Oceania/American_Samoa" },
          { name: "Australia", key: "au", route: "/Destinations/World_destinations/Oceania/Australia" },
          { name: "Cook Islands", key: "ck", route: "/Destinations/World_destinations/Oceania/Cook_Islands" },
          { name: "Fiji", key: "fj", route: "/Destinations/World_destinations/Oceania/Fiji" },
          { name: "French Polynesia", key: "pf", route: "/Destinations/World_destinations/Oceania/French_Polynesia" },
          { name: "Guam", key: "gu", route: "/Destinations/World_destinations/Oceania/Guam" },
          { name: "Kiribati", key: "ki", route: "/Destinations/World_destinations/Oceania/Kiribita" },
          { name: "Marshall Islands", key: "mh", route: "/Destinations/World_destinations/Oceania/Marhshall_Islands" },
          { name: "Micronesia", key: "fm", route: "/Destinations/World_destinations/Oceania/Micronesia" },
          { name: "Nauru", key: "nr", route: "/Destinations/World_destinations/Oceania/Nauru" },
          { name: "New Caledonia", key: "nc", route: "/Destinations/World_destinations/Oceania/New_Caledonia" },
          { name: "New Zealand", key: "nz", route: "/Destinations/World_destinations/Oceania/New_Zealand" },
          { name: "Niue", key: "nu", route: "/Destinations/World_destinations/Oceania/Niue" },
          { name: "Northern Mariana Islands", key: "mp", route: "/Destinations/World_destinations/Oceania/Northern_Mariana_Islands" },
          { name: "Palau", key: "pw", route: "/Destinations/World_destinations/Oceania/Palau" },
          { name: "Papua New Guinea", key: "pg", route: "/Destinations/World_destinations/Oceania/Papua_New_Guinea" },
          { name: "Samoa", key: "ws", route: "/Destinations/World_destinations/Oceania/Samoa" },
          { name: "Solomon Islands", key: "sb", route: "/Destinations/World_destinations/Oceania/Solomon_Islands" },
          { name: "Tokelau", key: "tk", route: "/Destinations/World_destinations/Oceania/Tokelau" },
          { name: "Tonga", key: "to", route: "/Destinations/World_destinations/Oceania/Tonga" },
          { name: "Tuvalu", key: "tv", route: "/Destinations/World_destinations/Oceania/Tuvalu" },
          { name: "Vanuatu", key: "vu", route: "/Destinations/World_destinations/Oceania/Vanuatu" },
          { name: "Wallis and Futuna", key: "wf", route: "/Destinations/World_destinations/Oceania/Wallis_and_Futuna" },
        ]
      },
      {
        
        name: "South America",
        key: "south-america",
        flyout: false,
        route: "/Destinations/World_destinations/South_America",
        sx: { backgroundColor: "#F18F01" },
        component: ContinentPage,
        children: [
          { name: "Argentina", key: "ar", route: "/Destinations/World_destinations/South_America/Argentina" },
          { name: "Bolivia", key: "bo", route: "/Destinations/World_destinations/South_America/Bolivia" },
          { name: "Brazil", key: "br", route: "/Destinations/World_destinations/South_America/Brazil" },
          { name: "Chile", key: "cl", route: "/Destinations/World_destinations/South_America/Chile" },
          { name: "Colombia", key: "co", route: "/Destinations/World_destinations/South_America/Colombia" },
          { name: "Ecuador", key: "ec", route: "/Destinations/World_destinations/South_America/Ecuador" },
          { name: "Falkland Islands", key: "fk", route: "/Destinations/World_destinations/South_America/Falkland_Islands" },
          { name: "French Guiana", key: "gf", route: "/Destinations/World_destinations/South_America/French_Guiana" },
          { name: "Guyana", key: "gy", route: "/Destinations/World_destinations/South_America/Guyana" },
          { name: "Paraguay", key: "py", route: "/Destinations/World_destinations/South_America/Paraguay" },
          { name: "Peru", key: "pe", route: "/Destinations/World_destinations/South_America/Peru" },
          { name: "Suriname", key: "sr", route: "/Destinations/World_destinations/South_America/Suriname" },
          { name: "Uruguay", key: "uy", route: "/Destinations/World_destinations/South_America/Uruguay" },
          { name: "Venezuela", key: "ve", route: "/Destinations/World_destinations/South_America/Venezuela" },
        ]
      }
    ]  //this is the end before this add 
  },

  // ─── one dynamic route for ALL continents ────────────────────
  {
    type: "route",
    key: "continent-dynamic",
    name: "ContinentPage",
    route: "/Destinations/World_destinations/:continent",
    component: ContinentPage,
  },
  //  ─── Only one Route for _all_ countries ────────────────────
  {
    type: "route",
    key: "country-dynamic",
    name: "CountryPage",
    route: "/Destinations/World_destinations/:continent/:countrySlug",
    component: CountryPage,
  },
  {
    type: "route",
    key: "pin-dynamic",
    name: "PinPage",
    route: "/Destinations/World_destinations/:continent/:countrySlug/:pinSlug",
    component: PinPage,
  },
  {
    
    name: "Profile",
    key: "profile",
    icon: <Icon fontSize="small">person</Icon>,
    route: "/profile",
    component: Profile,
  },
  /*{
    
    name: "Tables",
    key: "tables",
    icon: <Icon fontSize="small">table_view</Icon>,
    route: "/tables",
    component: Tables,
  },
  {
    
    name: "Billing",
    key: "billing",
    icon: <Icon fontSize="small">receipt_long</Icon>,
    route: "/billing",
    component: Billing,
  },
  {
    
    name: "RTL",
    key: "rtl",
    icon: <Icon fontSize="small">format_textdirection_r_to_l</Icon>,
    route: "/rtl",
    component: RTL,
  },
  {
    
    name: "Notifications",
    key: "notifications",
    icon: <Icon fontSize="small">notifications</Icon>,
    route: "/notifications",
    component: Notifications,
  }, */
  {
    
    name: "Sign In",
    key: "sign-in",
    icon: <Icon fontSize="small">login</Icon>,
    route: "/authentication/sign-in",
    component: SignIn,
  },
  {
    
    name: "Sign Up",
    key: "sign-up",
    icon: <Icon fontSize="small">assignment</Icon>,
    route: "/authentication/sign-up",
    component: SignUp,
  },
  {
    type: "route",
    name: "City Page",
    key: "city",
    route: "/city/:cityId",
    component: CityPage,
  },
];

export default routes;
