// Material Dashboard 2 React page components (no layout imports)
import React from "react";
import Tables from "./layouts/tables";
import Billing from "./layouts/billing";
import RTL from "./layouts/rtl";
import Notifications from "./layouts/notifications";
import Profile from "./layouts/profile";
import SignIn from "./layouts/authentication/sign-in";
import SignUp from "./layouts/authentication/sign-up";
import LocationOnIcon from '@mui/icons-material/LocationOn';
import PublicIcon from '@mui/icons-material/Public';
import CityPage from "components/CityPage";
import { AsiaPage, AfricaPage } from "components/continent";
import Home from "layouts/home";
import HomeIcon from "@mui/icons-material/Home";
import CountryPage from "components/countries/CountryPage";
import ContinentPage from "components/continent/ContinentPage";
import PinPage from "components/PinPage";
// @mui icons
import Icon from "@mui/material/Icon";

const Map = React.lazy(() => import("./layouts/map"));

const routes = [
  {
    type: "collapse",
    name: "Home",
    key: "home",
    icon: <HomeIcon fontSize="small">dashboard</HomeIcon>,
    route: "/home",
    component: Home,
  },
  {
    type: "collapse",
    name: "Map",
    key: "map",
    icon: <PublicIcon fontsize="small" />,
    route: "/map",
    component: Map,
  },
  {
    type: "collapse",
    name: "Destinations",
    key: "destinations",
    icon: <LocationOnIcon fontSize="small" />,
    flyout: false,
    children: [
      {
        type: "collapse",
        name: "Africa",
        key: "africa",
        flyout: true,
        children: [
          { name: "Overview", key: "africa-overview", type: "collapse", route: "/Destinations/World_destinations/Africa", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Algeria", key: "algeria", type: "collapse", route: "/Destinations/World_destinations/Africa/Algeria"},
          { name: "Angola", key: "angola", type: "collapse", route: "/Destinations/World_destinations/Africa/Angola" },
          { name: "Benin", key: "benin", type: "collapse", route: "/Destinations/World_destinations/Africa/Benin"},
          { name: "Botswana", key: "botswana", type: "collapse", route: "/Destinations/World_destinations/Africa/Botswana"},
          { name: "Burkina Faso", key: "burkinafaso", type: "collapse", route: "/Destinations/World_destinations/Africa/Burkina_Faso"},
          { name: "Burundi", key: "Burundi", type: "collapse", route: "/Destinations/World_destinations/Africa/Burundi"},
          { name: "Cameroon", key: "cameroon", type: "collapse", route: "/Destinations/World_destinations/Africa/Cameroon"},
          { name: "Cape Verde", key: "capeverde", type: "collapse", route: "/Destinations/World_destinations/Africa/Cape_Verde"},
          { name: "Central African Republic", key: "centralafricanrepublic", type: "collapse", route: "/Destinations/World_destinations/Africa/Central_African_Republic"},
          { name: "Chad", key: "chad", route: "/Destinations/World_destinations/Africa/Chad"},
          { name: "Comoros", key: "comoros", route: "/Destinations/World_destinations/Africa/Comoros"},
          { name: "Côte d'lvoire", key: "cotedlvoire", route: "/Destinations/World_destinations/Africa/Côte_d'lvoire"},
          { name: "Djibouti", key: "djibouti", route: "/Destinations/World_destinations/Africa/Djibouti"},
          { name: "Eswatini", key: "eswatini", route: "/Destinations/World destinations/Africa/Eswatini"},
          { name: "Egypt", key: "egypt", route: "/Destinations/World_destinations/Africa/Egypt"},
          { name: "Equatorial Guinea", key: "equatorial Guinea", route: "/Destinations/World_destinations/Africa/Equatorial_Guinea"},
          { name: "Eritrea", key: "eritrea", route: "/Destinations/World_destinations/Africa/Eritrea"},
          { name: "Ethiopia", key: "ethiopia", route: "/Destinations/World_destinations/Africa/Ethiopia"},
          { name: "Gabon", key: "gabon", route: "/Destinations/World_destinations/Africa/Gabon"},
          { name: "Ghana", key: "ghana", route: "/Destinations/World_destinations/Africa/Ghana"},
          { name: "Guinea", key: "guinea", route: "/Destinations/World_destinations/Africa/Guinea"},
          { name: "Guinea-Bissau", key: "guineabissau", route: "/Destinations/World_destinations/Africa/Guinea-Bissau"},
          { name: "Kenya", key: "kenya", route: "/Destinations/World_destinations/Africa/Kenya"},
          { name: "Lesotho", key: "lesotho", route: "/Destinations/World_destinations/Africa/Lesotho"},
          { name: "Liberia", key: "liberia", route: "/Destinations/World_destinations/Africa/Liberia"},
          { name: "Libya", key: "libya", route: "/Destinations/World_destinations/Africa/Libya"},
          { name: "Madagascar", key: "madagascar", route: "/Destinations/World_destinations/Africa/Madagascar"},
          { name: "Malawi", key: "malawi", route: "/Destinations/World_destinations/Africa/Malawi"},
          { name: "Mali", key: "mali", route: "/Destinations/World_destinations/Africa/Mali"},
          { name: "Mauritania", key: "mauritania", route: "/Destinations/World_destinations/Africa/Mouritania"},
          { name: "Mauritius", key: "mauritius", route: "/Destinations/World_destinations/Africa/Mauritius"},
          { name: "Morocco", key: "morocco", route: "/Destinations/World_destinations/Africa/Morocco"},
          { name: "Mozambique", key: "mozambique", route: "/Destinations/World_destinations/Africa/Mozambique"},
          { name: "Namibia", key: "namibia", route: "/Destinations/World_destinations/Africa/Namibia"},
          { name: "Niger", key: "niger", route: "/Destinations/World_destinations/Africa/Niger"},
          { name: "Nigeria", key: "nigeria", route: "/Destinations/World_destinations/Africa/Nigeria"},
          { name: "Rwanda", key: "Rwanda", route: "/Destinations/World_destinations/Africa/Rwanda"},
          { name: "São Tomé and Príncipe", key: "saotomeandprincipe", route: "/Destinations/World_destinations/Africa/São_Tomé_and_Príncipe"},
          { name: "Senegal", key: "senegal", route: "/Destinations/World_destinations/Africa/Senegal"},
          { name: "Seychelles", key: "seychelles", routes: "/Destinations/World_destinations/Africa/Seychelles"},
          { name: "Sierra Leone", key: "sierraleona", routes: "/Destinations/World_destinations/Africa/Sierra_Leone"},
          { name: "Somalia", key: "somalia", route: "/Destinations/World_destinations/Africa/Somalia"},
          { name: "South Africa", key: "southafrica", route: "/Destinations/World_destinations/Africa/South_Africa"},
          { name: "Sudan", key: "sudan", route: "/Destinations/World_destinations/Africa/Sudan"},
          { name: "Tanzania", key: "tanzania", route: "/Destinations/World_destinations/Africa/Tanzania"},
          { name: "Togo", key: "togo", route: "/Destinations/World_destinations/Africa/Togo"},
          { name: "Tunisia", key: "tunisia", route: "/Destinations/World_destinations/Africa/Tunisia"},
          { name: "Uganda", key: "uganda", route: "/Destinations/World_destinations/Africa/Uganda"},
          { name: "Zambia", key: "zambia", route: "/Destinations/World_destinations/Africa/Zambia"},
          { name: "Zimbabwe", key: "zimbabwe", route: "/Destinations/World_destinations/Africa/Zimbabwe"}
        ]
      },
      {
        type: "collapse",
        name: "Antarctica",
        key: "antarctica",
        flyout: true,
        children: [
          { name: "Overview", key: "Antarcica-overview", type: "collapse", route: "/Destinations/World_destinations/Antarctica", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Antarctica", key: "antarctica", route: "/Destinations/World_destinations/Antarctica/Antarctica" }
        ]
      },
      {
        type: "collapse",
        name: "Asia",
        key: "asia",
        route: "/Destinations/World_destinations/Asia",
        component: AsiaPage,
        flyout: true,
        children: [
          { name: "Overview", key: "asia-overview", type: "collapse", route: "/Destinations/World_destinations/Asia", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Afghanistan", key: "afghanistan", route: "/Destinations/World_destinations/Asia/Afghanistan"},
          { name: "Azerbaijan", key: "azerbaijan", route: "/Destinations/World_destinations/Asia/Azerbaijan"},
          { name: "Bangladesh", key: "bangladesh", route: "/Destinations/World_destinations/Asia/Bangladesh"},
          { name: "Bhutan", key: "bhutan", route: "/Destinations/World_destinations/Asia/Bhutan"},
          { name: "Brunei", key: "brunei", route: "/Destinations/World_destinations/Asia/Brunei"},
          { name: "Cambodia", key: "cambodia", route: "/Destinations/World_destinations/Asia/Cambodia"},
          { name: "China", key: "china", route: "/Destinations/World_destinations/Asia/China"},
          { name: "East Timor", key: "easttimor", route: "/Destinations/World_destinations/Asia/East_Timor"},
           {name: "Hong Kong", key: "hongkong", route: "/Destinations/World_destinations/Asia/Hong_Kong"},
          { name: "India", key: "india", route: "/Destinations/World_destinations/Asia/India"},
          { name: "Indonesia", key: "indonesia", route: "/Destinations/World_destinations/Asia/Indonesia"},
          { name: "Japan", key: "japan", route: "/Destinations/World_destinations/Asia/Japan"},
          { name: "Kazakhstan", key: "kazakhstan", route: "/Destinations/World_destinations/Asia/Kazakhstan"},
          { name: "Kyrgyzstan", key: "kyrgyzstan", route: "/Destinations/World_destinations/Asia/Kyrgyzstan"},
          { name: "Laos", key: "laos", route: "/Destinations/World_destinations/Asia/Laos"},
          {name: "Macau", key: "macau", route: "/Destinations/World_destinations/Asia/Macau"},
          { name: "Malaysia", key: "malaysia", route: "/Destinations/World_destinations/Asia/Malaysia"},
          { name: "Maldives", key: "maldives", route: "/Destinations/World_destinations/Asia/Maldives"},
          { name: "Mongolia", key: "mongolia", route: "/Destinations/World_destinations/Asia/Mongolia"},
          { name: "Myanmar", key: "myanmar", route: "/Destinations/World_destinations/Asia/Myanmar"},
          { name: "Nepal", key: "nepal", route: "/Destinations/World_destinations/Asia/Nepal"},
          { name: "North Korea", key: "northkorea", route: "/Destinations/World_destinations/Asia/North_Korea"},
          { name: "Pakistan", key: "pakistan", route: "/Destinations/World_destinations/Asia/Pakistan"},
          { name: "Philippines", key: "philippines", route: "/Destinations/World_destinations/Asia/Philippines"},
          { name: "Singapore", key: "singapore", route: "/Destinations/World_destinations/Asia/Singapore"},
          { name: "South Korea", key: "southkorea", route: "/Destinations/World_destinations/Asia/South_Korea"},
          { name: "Sri Lanka", key: "srilanka", route: "/Destinations/World_destinations/Asia/Sri Lanka"},
          { name: "Taiwan", key: "taiwan", route: "/Destinations/World_destinations/Asia/Taiwan"},
          { name: "Tajikistan", key: "tajikistan", route: "/Destinations/World_destinations/Asia/tajikistan"},
          { name: "Thailand", key: "thailand", route: "/Destinations/World_destinations/Asia/Thailand"},
          {name: "Tibet", key: "tibet", route: "/Destinations/World_destinations/Asia/Tibet",},
          { name: "Turkmenistan", key: "turkmenistan", route: "/Destinations/World_destinations/Asia/Turkmenistan"},
          { name: "Uzbekistan", key: "uzbekistan", route: "/Destinations/World_destinations/Asia/Uzbekistan"},
          { name: "Vietnam", key: "vietnam", route: "/Destinations/World_destinations/Asia/Vietnam"}
        ]
      },
      {
        type: "collapse",
        name: "Caribbean",
        key: "caribbean",
        flyout: true,
        children: [
          { name: "Caribbean", key: "caribbean-overview", type: "collapse", route: "/Destinations/World_destinations/Caribbean", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Antigua and Barbuda", key: "antigua-and-barbuda", route: "/Destinations/World_destinations/Caribbean/Antigua_and_Barbuda"},
           {name: "Aruba", key: "aruba", route: "/Destinations/World_destinations/Caribbean/Aruba"},
          { name: "Bahamas", key: "bahamas", route: "/Destinations/World_destinations/Caribbean/Bahamas"},
          { name: "Barbados", key: "barbados", route: "/Destinations/World_destinations/Caribbean/Barbados"},
           {name: "Bermuda", key: "bermuda", route: "/Destinations/World_destinations/Caribbean/Bermuda"},
          { name: "British Virgin Islands", key: "britishvirginislands", route: "/Destinations/World_destinations/Caribbean/British_Virgin_Islands"},
          {name: "Caribbean Netherlands", key: "caribbeannetherlands", route: "/Destinations/World_destinations/Caribbean/Caribbean_Netherlands"},
          {name: "Cayman Islands", key: "caymanislands", route: "/Destinations/World_destinations/Caribbean/Cayman_Islands"},
          { name: "Cuba", key: "cuba", route: "/Destinations/World_destinations/Caribbean/Cuba"},
          {name: "Curaçao", key: "curacao", route: "/Destinations/World_destinations/Caribbean/Curaçao"},
          { name: "Dominica", key: "dominica", route: "/Destinations/World_destinations/Caribbean/Dominica"},
          { name: "Dominican Republic", key: "dominicanrepublic", route: "/Destinations/World_destinations/Caribbean/Dominican_Republic"},
          { name: "Grenada", key: "grenada", route: "/Destinations/World_destinations/Caribbean/Grenada"},
          { name: "Guadeloupe", key: "guadeloupe", route: "/Destinations/World_destinations/Caribbean/Guadeloupe"},
          { name: "Haiti", key: "haitit", route: "/Destinations/World_destinations/Caribbean/Haiti"},
          { name: "Jamaica", key: "jamaica", route: "/Destinations/World_destinations/Caribbean/Jamaica"},
          { name: "Martinique", key: "martinique", route: "/Destinations/World_destinations/Caribbean/Martinique"},
          { name: "Montserrat", key: "montserrat", route: "/Destinations/World_destinations/Caribbean/Montserrat"},
          { name: "Puerto Rico", key: "puertorico", route: "/Destinations/World_destinations/Caribbean/Puerto_Rico"},
          { name: "Saint Lucia", key: "saintlucia", route: "/Destinations/World_destinations/Caribbean/Saint Lucia"},
          { name: "Saint Vincent and the Grenadines", key: "saintvincentandthegrenadines", route: "/Destinations/World_destinations/Caribbean/Saint_Vincent_and_the_Grenadines"},
          { name: "Sint Maarten", key: "sintmaarten", route: "/Destinations/World_destinations/Caribbean/Sint_Maarten"},
          { name: "Trinidad and Tobago", key: "trinidadandtobago", route: "/Destinations/World_destinations/Caribbean/Trinidad and Tobago"},
          { name: "Turks and Caicos Islands", key: "turksandcaicosislands", route: "/Destinations/World_destinations/Caribbean/Turks_and_Caicos_Islands"}
        ]
      },
      {
        type: "collapse",
        name: "Central America",
        key: "central-america",
        flyout: true,
        children: [
          { name: "Overview", key: "central-america-overview", type: "collapse", route: "/Destinations/World_destinations/Cental_America", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Belize", key: "belize", route: "/Destinations/World_destinations/Central_America/Belize"},
          { name: "Costa Rica", key: "costarica", route: "/Destinations/World_destinations/Central_America/Costa_Rica"},
          { name: "El Salvador", key: "elsalvador", route: "/Destinations/World_destinations/Central_America/El_Salvador"},
          { name: "Guatemala", key: "guatemala", route: "/Destinations/World_destinations/Central_America/Guatemala"},
          { name: "Honduras", key: "honduras", route: "/Destinations/World_destinations/Central_America/Honduras"},
          { name: "Nicaragua", key: "nicaragua", route: "/Destinations/World_destinations/Central_America/Nicaragua"},
          { name: "Panama", key: "panama", route: "/Destinations/World_destinations/Central_America/Panama"}
        ]
      },
      {
        type: "collapse",
        name: "Europe",
        key: "europe",
        flyout: true,
        children: [
          { name: "Overview", key: "europe-overview", type: "collapse", route: "/Destinations/World_destinations/Europe", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          {name: "Åland Islands", key: "alandislands", route: "/Destinations/World_destinations/Europe/Åland Islands"},
          { name: "Albania", key: "albania", route: "/Destinations/World_destinations/Europe/Albania"},
          { name: "Andorra", key: "andorra", route: "/Destinations/World_destinations/Europe/Andorra"},
          { name: "Armenia", key: "armenia", route: "/Destinations/World_destinations/Europe/Armenia"},
          { name: "Austria", key: "austria", route: "/Destinations/World_destinations/Europe/Austria"},
          { name: "Belarus", key: "belarus", route: "/Destinations/World_destinations/Europe/Belarus"},
          { name: "Belgium", key: "belgium", route: "/Destinations/World_destinations/Europe/Belgium"},
          { name: "Bosnia and Herzegovina", key: "bosniaandherzegovina", route: "/Destinations/World_destinations/Europe/Bosnia_and_Herzegovina"},
          { name: "Bulgaria", key: "bulgaria", route: "/Destinations/World_destinations/Europe/Bulgaria"},
          {name: "Crimea", key: "crimea", route: "/Destinations/World_destinations/Europe/Crimea"},
          { name: "Croatia", key: "croatia", route: "/Destinations/World_destinations/Europe/Croatia"},
          { name: "Cyprus", key: "cyprus", route: "/Destinations/World_destinations/Europe/Cyprus"},
          { name: "Czechia", key: "czechia", route: "/Destinations/World_destinations/Europe/Czechia"},
          { name: "Denmark", key: "denmark", route: "/Destinations/World_destinations/Europe/Denmark"},
          { name: "Estonia", key: "estonia", route: "/Destinations/World_destinations/Europe/Estiona"},
          {name: "Faroe Islands", key: "faroeislands", route: "/Destinations/World_destinations/Europe/Faroe Islands"},
          { name: "Finland", key: "finland", route: "/Destinations/World_destinations/Europe/Finland"},
          { name: "France", key: "france", route: "/Destinations/World_destinations/Europe/France"},
          { name: "Georgia", key: "georgia", route: "/Destinations/World_destinations/Europe/Georgia"},
          { name: "Germany", key: "germany", route: "/Destinations/World_destinations/Europe/Germany"},
          { name: "Greece", key: "greece", route: "/Destinations/World_destinations/Europe/Greece"},
          { name: "Greenland", key: "greenland", route: "/Destinations/World_destinations/Europe/Greenland"},
          {name: "Guernsey", key: "guernsey", route: "/Destinations/World_destinations/Europe/Guernsey"},
          { name: "Hungary", key: "hungary", route: "/Destinations/World_destinations/Europe/Hungary"},
          { name: "Iceland", key: "iceland", route: "/Destinations/World_destinations/Europe/Iceland"},
          { name: "Ireland", key: "ireland", route: "/Destinations/World_destinations/Europe/Ireland"},
          { name: "Italy", key: "italy", route: "/Destinations/World_destinations/Europe/Italy"},
          {name: "Jersey", key: "jersey", route: "/Destinations/World_destinations/Europe/Jersey"},
          { name: "Kosovo", key: "kosovo", route: "/Destinations/World_destinations/Europe/Kosovo"},
          { name: "Latvia", key: "latvia", route: "/Destinations/World_destinations/Europe/Latvia"},
          { name: "Liechtenstein", key: "liechtenstein", route: "/Destinations/World_destinations/Europe/Liechtenstein"},
          { name: "Lithuania", key: "lithuania", route: "/Destinations/World_destinations/Europe/Lithuania"},
          { name: "Luxembourg", key: "luxembourg", route: "/Destinations/World_destinations/Europe/Luxembourg"},
          { name: "Malta", key: "malta", route: "/Destinations/World_destinations/Europe/Malta"},
          { name: "Moldova", key: "moldova", route: "/Destinations/World_destinations/Europe/Moldova"},
          { name: "Monaco", key: "monaco", route: "/Destinations/World_destinations/Europe/Monaco"},
          { name: "Montenegro", key: "montenegro", route: "/Destinations/World_destinations/Europe/Montenegro"},
          { name: "Netherlands", key: "amsterdam", route: "/Destinations/World_destinations/Europe/Netherlands"},
          { name: "North Macedonia", key: "northmacedonia", route: "/Destinations/World_destinations/Europe/North_Macedonia"},
          { name: "Norway", key: "norway", route: "/Destinations/World_destinations/Europe/Norway"},
          { name: "Poland", key: "poland", route: "/Destinations/World_destinations/Europe/Poland"},
          { name: "Portugal", key: "portugal", route: "/Destinations/World_destinations/Europe/Portugal"},
          { name: "Romania", key: "romania", route: "/Destinations/World_destinations/Europe/Romania"},
          { name: "Russia", key: "russia", route: "/Destinations/World_destinations/Europe/Russia"},
          { name: "San Marino", key: "sanmarino", route: "/Destinations/World_destinations/Europe/San_Marino"},
          { name: "Serbia", key: "serbia", route: "/Destinations/World_destinations/Europe/Serbia"},
          { name: "Slovakia", key: "slovakia", route: "/Destinations/World_destinations/Europe/Slovakia"},
          { name: "Slovenia", key: "slovenia", route: "/Destinations/World_destinations/Europe/Slovenia"},
          { name: "Spain", key: "spain", route: "/Destinations/World_destinations/Europe/Spain"},
          { name: "Sweden", key: "sweden", route: "/Destinations/World_destinations/Europe/Sweden",},
          { name: "Switzerland", key: "switzerland", route: "/Destinations/World_destinations/Europe/Switzerland"},
          { name: "Ukraine", key: "ukraine", route: "/Destinations/World_destinations/Europe/Ukraine"},
          { name: "United Kingdom", key: "unitedkingdom", route: "/Destinations/World_destinations/Europe/United_Kingdom"},
          { name: "Vatican City", key: "vaticancity", route: "/Destinations/World_destinations/Europe/Vatican_City"}
        ]
      },
      {
        type: "collapse",
        name: "Middle East",
        key: "middle-east",
        flyout: true,
        children: [
          { name: "Overview", key: "middle-east-overview", type: "collapse", route: "/Destinations/World_destinations/Middle_East", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Bahrain", key: "bahrain", route: "/Destinations/World_destinations/Middle_East/Bahrain"},
          {name: "Golan", key: "golan", route: "/Destinations/World_destinations/Middle_East/Golan"},
          { name: "Iran", key: "iran", route: "/Destinations/World_destinations/Middle_East/Iran"},
          { name: "Iraq", key: "iraq", route: "/Destinations/World_destinations/Middle_East/Iraq"},
          { name: "Israel", key: "israel", route: "/Destinations/World_destinations/Middle_East/Israel"},
          { name: "Jordan", key: "jordan", route: "/Destinations/World_destinations/Middle_East/Jordan"},
          { name: "Kuwait", key: "kuwait", route: "/Destinations/World_destinations/Middle_East/Kuwait"},
          { name: "Lebanon", key: "lebanon", route: "/Destinations/World_destinations/Middle_East/Lebanon"},
          { name: "Oman", key: "oman", route: "/Destinations/World_destinations/Middle_East/Oman"},
          { name: "Qatar", key: "qatar", route: "/Destinations/World_destinations/Middle_East/Qatar"},
          { name: "Saudi Arabia", key: "saudiarabia", route: "/Destinations/World_destinations/Middle_East/Saudi_Arabia"},
          { name: "Syria", key: "syria", route: "/Destinations/World_destinations/Middle_East/Syria"},
          { name: "Turkey", key: "turkey", route: "/Destinations/World_destinations/Middle_East/Turkey"},
          { name: "United Arab Emirates", key: "unitedarabemirates", route: "/Destinations/World_destinations/Middle_East/United_Arab_Emirates"},
          { name: "Yemen", key: "yemen", route: "/Destinations/World_destinations/Middle_East/Yemen"}
        ]
      },
      {
        type: "collapse",
        name: "North America",
        key: "north-america",
        flyout: true,
        children: [
          { name: "Overview", key: "north-america-overview", type: "collapse", route: "/Destinations/World_destinations/North_America", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Canada", key: "canada", route: "/Destinations/World_destinations/North_America/Canada"},
          { name: "Mexico", key: "mexico", route: "/Destinations/World_destinations/North_America/Mexico"},
          { name: "United States", key: "unitedstates", route: "/Destinations/World_destinations/North_America/United_States"}
        ]
      },
      {
        type: "collapse",
        name: "Oceania",
        key: "oceania",
        flyout: true,
        children: [
          { name: "Overview", key: "oceania-overview", type: "collapse", route: "/Destinations/World_destinations/Oceania", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Australia", key: "australia", route: "/Destinations/World_destinations/Oceania/Australia"},
          { name: "Fiji", key: "fiji", route: "/Destinations/World_destinations/Oceania/Fiji"},
          { name: "French Polynesia", key: "frenchpolynesia", route: "/Destinations/World_destinations/Oceania/French_Polynesia"},
          {name: "Marshall Islands", key: "marshallislands", route: "/Destinations/World_destinations/Oceania/Marshall_Islands"},
          { name: "Micronesia", key: "micronesia", route: "/Destinations/World_destinations/Oceania/Micronesia"},
          { name: "New Caledonia", key: "newcaledonia", route: "/Destinations/World_destinations/Oceania/New _aledonia"},
          { name: "New Zealand", key: "newzealand", route: "/Destinations/World_destinations/Oceania/New Zealand"},
          { name: "Palau", key: "palau", route: "/Destinations/World_destinations/Oceania/Palau"},
          { name: "Papua New Guinea", key: "papuanewguinea", route: "/Destinations/World_destinations/Oceania/Papua_New_Guinea"},
          {name: "Pitcairn Islands", key: "pitcairnislands", route: "/Destinations/World_destinations/Oceania/Pitcairn_Islands"},
          { name: "Samoa", key: "samoa", route: "/Destinations/World_destinations/Oceania/Samoa"},
          { name: "Solomon Islands", key: "solomonislands", route: "/Destinations/World_destinations/Oceania/Solomon_Islands"},
          { name: "Tonga", key: "tonga", route: "/Destinations/World_destinations/Oceania/Tonga"},
          { name: "Tuvalu", key: "tuvalu", route: "/Destinations/World_destinations/Oceania/Tuvalu"},
          { name: "Vanuatu", key: "vanuatu", route: "/Destinations/World_destinations/Oceania/Vanuatu"}
        ]
      },
      {
        type: "collapse",
        name: "South America",
        key: "south-america",
        flyout: true,
        children: [
          { name: "Overview", key: "south-america-overview", type: "collapse", route: "/Destinations/World_destinations/South_America", sx: {backgroundColor: "rgba(241,143,1,1)"}},
          { name: "Argentina", key: "argentina", route: "/Destinations/World_destinations/South_America/Argentina"},
          { name: "Bolivia", key: "bolivia", route: "/Destinations/World_destinations/South_America/Bolivia"},
          { name: "Brazil", key: "brazil", route: "/Destinations/World_destinations/South_America/Brazil"},
          { name: "Chile", key: "chile", route: "/Destinations/World_destinations/South_America/Chile"},
          { name: "Ecuador", key: "ecuador", route: "/Destinations/World_destinations/South_America/Ecuador"},
          { name: "Falkland Islands", key: "falklandislands", route: "/Destinations/World_destinations/South_America/Falkland Islands"},
          { name: "Guyana", key: "guyana", route: "/Destinations/World_destinations/South_America/Guyana"},
          { name: "Paraguay", key: "paraguay", route: "/Destinations/World_destinations/South_America/Paraguay"},
          { name: "Peru", key: "peru", route: "/Destinations/World_destinations/South_America/Peru"},
          { name: "Suriname", key: "suriname", route: "/Destinations/World_destinations/South_America/Suriname"},
          { name: "Uruguay", key: "uruguay", route: "/Destinations/World_destinations/South_America/Uruguay"},
          { name: "Venezuela", key: "venezuala", route: "/Destinations/World_destinations/South_America/Venezuela"}
        ]
      }
    ]  //this is the end before this add 
  },

  // ─── one dynamic route for ALL continents ────────────────────
  {
  type: "route",
  key: "continent-dynamic",
  name: "ContinentPage",
  route: "/Destinations/World_destinations/:continent",
  component: ContinentPage,
},
    //  ─── Only one Route for _all_ countries ────────────────────
  {
    type: "route",
    key: "country-dynamic",
    name: "CountryPage",
    route: "/Destinations/World_destinations/:continent/:countrySlug",
    component: CountryPage,
  },
  {
    type: "route",
    key: "pin-dynamic",
    name: "PinPage",
    route: "/Destinations/World_destinations/:continent/:countrySlug/:pinSlug",
    component: PinPage,
  },
  {
    type: "collapse",
    name: "Profile",
    key: "profile",
    icon: <Icon fontSize="small">person</Icon>,
    route: "/profile",
    component: Profile,
  },
  /*{
    type: "collapse",
    name: "Tables",
    key: "tables",
    icon: <Icon fontSize="small">table_view</Icon>,
    route: "/tables",
    component: Tables,
  },
  {
    type: "collapse",
    name: "Billing",
    key: "billing",
    icon: <Icon fontSize="small">receipt_long</Icon>,
    route: "/billing",
    component: Billing,
  },
  {
    type: "collapse",
    name: "RTL",
    key: "rtl",
    icon: <Icon fontSize="small">format_textdirection_r_to_l</Icon>,
    route: "/rtl",
    component: RTL,
  },
  {
    type: "collapse",
    name: "Notifications",
    key: "notifications",
    icon: <Icon fontSize="small">notifications</Icon>,
    route: "/notifications",
    component: Notifications,
  }, */
  {
    type: "collapse",
    name: "Sign In",
    key: "sign-in",
    icon: <Icon fontSize="small">login</Icon>,
    route: "/authentication/sign-in",
    component: SignIn,
  },
  {
    type: "collapse",
    name: "Sign Up",
    key: "sign-up",
    icon: <Icon fontSize="small">assignment</Icon>,
    route: "/authentication/sign-up",
    component: SignUp,
  },
  {
    type: "route",
    name: "City Page",
    key: "city",
    route: "/city/:cityId",
    component: CityPage,
  },
];

export default routes;
